// Generated by CoffeeScript 1.7.1

/*
	hash-tabs

	Gruntfile.coffee

	@author Sean
	
	@note Created on 2014-06-07 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  "use strict";
  module.exports = function(grunt) {
    require("load-grunt-tasks")(grunt);
    require("time-grunt")(grunt);
    grunt.initConfig({
      pkg: grunt.file.readJSON("package.json"),
      banner: "/*! <%= pkg.name %> - v<%= pkg.version %> - " + "<%= grunt.template.today(\"yyyy-mm-dd\") %>\n" + "<%= pkg.homepage ? \"* \" + pkg.homepage + \"\\n\" : \"\" %>" + "* Copyright (c) <%= grunt.template.today(\"yyyy\") %> <%= pkg.author.name %>;" + " Licensed MIT */\n",
      clean: {
        files: ["dist"]
      },
      concat: {
        options: {
          banner: "<%= banner %>",
          stripBanners: true
        },
        dist: {
          src: ["src/<%= pkg.name %>.js"],
          dest: "dist/jquery.<%= pkg.name %>.js"
        }
      },
      uglify: {
        options: {
          banner: "<%= banner %>"
        },
        dist: {
          src: "<%= concat.dist.dest %>",
          dest: "dist/jquery.<%= pkg.name %>.min.js"
        }
      },
      qunit: {
        all: {
          options: {
            urls: ["http://localhost:9000/test/<%= pkg.name %>.html"]
          }
        }
      },
      jshint: {
        options: {
          reporter: require("jshint-stylish")
        },
        gruntfile: {
          options: {
            jshintrc: ".jshintrc"
          },
          src: "Gruntfile.js"
        },
        src: {
          options: {
            jshintrc: "src/.jshintrc"
          },
          src: ["src/**/*.js"]
        },
        test: {
          options: {
            jshintrc: "test/.jshintrc"
          },
          src: ["test/**/*.js"]
        }
      },
      watch: {
        gruntfile: {
          files: "<%= jshint.gruntfile.src %>",
          tasks: ["jshint:gruntfile"]
        },
        src: {
          files: "<%= jshint.src.src %>",
          tasks: ["jshint:src", "qunit"]
        },
        test: {
          files: "<%= jshint.test.src %>",
          tasks: ["jshint:test", "qunit"]
        }
      },
      connect: {
        server: {
          options: {
            hostname: "*",
            port: 9000
          }
        }
      }
    });
    grunt.registerTask("default", ["jshint", "connect", "qunit", "clean", "concat", "uglify"]);
    grunt.registerTask("server", function() {
      grunt.log.warn("The `server` task has been deprecated. Use `grunt serve` to start a server.");
      grunt.task.run(["serve"]);
    });
    grunt.registerTask("serve", ["connect", "watch"]);
    return grunt.registerTask("test", ["jshint", "connect", "qunit"]);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.map
