// Generated by CoffeeScript 1.7.1

/*
	hash-tabs

	demo.coffee

	@author Sean Goresht

	@note Created on 2014-06-07 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  jQuery(document).ready(function() {
    var $animationExamples, $example1, $example2;
    $example1 = $(".example1").hashTabs();
    $example2 = $(".example2").hashTabs({
      smoothScroll: {
        enabled: true,
        initialTabId: "smooth-scroller"
      }
    });
    return $animationExamples = $(".animated-tab").hashTabs();
  });

}).call(this);

//# sourceMappingURL=demo.map
