// Generated by CoffeeScript 1.7.1

/*
	hash-tabs

	demo.coffee

	@author Sean
	
	@note Created on 2014-06-07 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  jQuery(document).ready(function() {
    var $tabs;
    return $tabs = $(".tab-container").hashTabs({
      debug: true
    });
  });

}).call(this);

//# sourceMappingURL=demo.map
